### ISSUE TITLE
license

### ISSUE THREAD

**Issue by devkral** [melfm/pulse-detector#1]
What is the software license of this project?
Sry for bothering you.
I use it in an university project.

**Comment by melfm** [comment]
This is licensed under The MIT License (MIT), so free to use.

Best Regards,

Melissa Mozifian

**Comment by Hub-er** [comment]
thanks for your pulse-detector, it is so intresting!
but why it is so long un-updated?

**Comment by melfm** [comment]
This was my undergrad project, the original version of this code is in Python and well-maintained. https://github.com/thearn/webcam-pulse-detector
